/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cache_server_CONSTANTS_H
#define cache_server_CONSTANTS_H

#include "cache_server_types.h"

namespace aos {

class cache_serverConstants {
 public:
  cache_serverConstants();

};

extern const cache_serverConstants g_cache_server_constants;

} // namespace

#endif
