/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cache_server_constants.h"

namespace aos {

const cache_serverConstants g_cache_server_constants;

cache_serverConstants::cache_serverConstants() {
}

} // namespace

