/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cache_server_H
#define cache_server_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "cache_server_types.h"

namespace aos {

#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class cache_serverIf {
 public:
  virtual ~cache_serverIf() {}
  virtual void ping(std::string& _return, const std::string& url) = 0;
};

class cache_serverIfFactory {
 public:
  typedef cache_serverIf Handler;

  virtual ~cache_serverIfFactory() {}

  virtual cache_serverIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(cache_serverIf* /* handler */) = 0;
};

class cache_serverIfSingletonFactory : virtual public cache_serverIfFactory {
 public:
  cache_serverIfSingletonFactory(const boost::shared_ptr<cache_serverIf>& iface) : iface_(iface) {}
  virtual ~cache_serverIfSingletonFactory() {}

  virtual cache_serverIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(cache_serverIf* /* handler */) {}

 protected:
  boost::shared_ptr<cache_serverIf> iface_;
};

class cache_serverNull : virtual public cache_serverIf {
 public:
  virtual ~cache_serverNull() {}
  void ping(std::string& /* _return */, const std::string& /* url */) {
    return;
  }
};

typedef struct _cache_server_ping_args__isset {
  _cache_server_ping_args__isset() : url(false) {}
  bool url :1;
} _cache_server_ping_args__isset;

class cache_server_ping_args {
 public:

  cache_server_ping_args(const cache_server_ping_args&);
  cache_server_ping_args& operator=(const cache_server_ping_args&);
  cache_server_ping_args() : url() {
  }

  virtual ~cache_server_ping_args() throw();
  std::string url;

  _cache_server_ping_args__isset __isset;

  void __set_url(const std::string& val);

  bool operator == (const cache_server_ping_args & rhs) const
  {
    if (!(url == rhs.url))
      return false;
    return true;
  }
  bool operator != (const cache_server_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const cache_server_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class cache_server_ping_pargs {
 public:


  virtual ~cache_server_ping_pargs() throw();
  const std::string* url;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _cache_server_ping_result__isset {
  _cache_server_ping_result__isset() : success(false) {}
  bool success :1;
} _cache_server_ping_result__isset;

class cache_server_ping_result {
 public:

  cache_server_ping_result(const cache_server_ping_result&);
  cache_server_ping_result& operator=(const cache_server_ping_result&);
  cache_server_ping_result() : success() {
  }

  virtual ~cache_server_ping_result() throw();
  std::string success;

  _cache_server_ping_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const cache_server_ping_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const cache_server_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const cache_server_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _cache_server_ping_presult__isset {
  _cache_server_ping_presult__isset() : success(false) {}
  bool success :1;
} _cache_server_ping_presult__isset;

class cache_server_ping_presult {
 public:


  virtual ~cache_server_ping_presult() throw();
  std::string* success;

  _cache_server_ping_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class cache_serverClient : virtual public cache_serverIf {
 public:
  cache_serverClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  cache_serverClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping(std::string& _return, const std::string& url);
  void send_ping(const std::string& url);
  void recv_ping(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class cache_serverProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<cache_serverIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (cache_serverProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  cache_serverProcessor(boost::shared_ptr<cache_serverIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &cache_serverProcessor::process_ping;
  }

  virtual ~cache_serverProcessor() {}
};

class cache_serverProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  cache_serverProcessorFactory(const ::boost::shared_ptr< cache_serverIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< cache_serverIfFactory > handlerFactory_;
};

class cache_serverMultiface : virtual public cache_serverIf {
 public:
  cache_serverMultiface(std::vector<boost::shared_ptr<cache_serverIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~cache_serverMultiface() {}
 protected:
  std::vector<boost::shared_ptr<cache_serverIf> > ifaces_;
  cache_serverMultiface() {}
  void add(boost::shared_ptr<cache_serverIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping(std::string& _return, const std::string& url) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping(_return, url);
    }
    ifaces_[i]->ping(_return, url);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class cache_serverConcurrentClient : virtual public cache_serverIf {
 public:
  cache_serverConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  cache_serverConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping(std::string& _return, const std::string& url);
  int32_t send_ping(const std::string& url);
  void recv_ping(std::string& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif

} // namespace

#endif
